---

# Gather Interface by filter:
#
# * aws_vpc_route_tables loop variable: 'rt'
# * aws_vpc_route_tables.routes loop variable: 'interface'
#
# Returns:
# * aws_vpc_rt_interface_by_filter

- name: gather interface by filter
  ec2_eni_facts:
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit)  }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_route_table_profile | default(omit) }}"
    region: "{{ rt.region | default(aws_vpc_route_table_default_region) }}"
    filters: "{{ interface.filter | get_attr('key', 'val') }}"
  register: _aws_vpc_rt_routes_interface
  check_mode: False

- name: fail if not exactly one interface was found by filter
  assert:
    that:
      - _aws_vpc_rt_routes_interface.network_interfaces is defined
      - _aws_vpc_rt_routes_interface.network_interfaces | length == 1
    msg: Not exactly one interface has been found

- name: set interface array
  set_fact:
    aws_vpc_rt_interface_by_filter: "{{ aws_vpc_rt_interface_by_filter | default([]) + [{'dest': interface.dest, 'interface_id': _aws_vpc_rt_routes_interface.network_interfaces[0].network_interface_id }] }}"
