---

###
### Loop over routes
###

# IGW
#
# Returns:
# * aws_vpc_rt_igw
- include_tasks: _facts_route_igw.yml
  loop_control:
    loop_var: igw
  with_items:
    - "{{ rt.routes }}"
  when:
    - igw.type == 'igw'


# NAT by Name tag
#
# Returns:
# * aws_vpc_rt_nat_by_name
- include_tasks: _facts_route_nat_by_name.yml
  loop_control:
    loop_var: nat
  with_items:
    - "{{ rt.routes }}"
  when:
    - nat.type == 'nat'
    - nat.name is defined

# NAT by filter
#
# Returns:
# * aws_vpc_rt_nat_by_filter
- include_tasks: _facts_route_nat_by_filter.yml
  loop_control:
    loop_var: nat
  with_items:
    - "{{ rt.routes }}"
  when:
    - nat.type == 'nat'
    - nat.filter is defined


# Peering by Name tag
#
# Returns:
# * aws_vpc_rt_peering_by_name
- include_tasks: _facts_route_peering_by_name.yml
  loop_control:
    loop_var: peering
  with_items:
    - "{{ rt.routes }}"
  when:
    - peering.type == 'peering'
    - peering.name is defined

# Peering by filter
#
# Returns:
# * aws_vpc_rt_peering_by_filter
- include_tasks: _facts_route_peering_by_filter.yml
  loop_control:
    loop_var: peering
  with_items:
    - "{{ rt.routes }}"
  when:
    - peering.type == 'peering'
    - peering.filter is defined


# Instance by Name tag
#
# Returns:
# * aws_vpc_rt_instance_by_name
- include_tasks: _facts_route_instance_by_name.yml
  loop_control:
    loop_var: instance
  with_items:
    - "{{ rt.routes }}"
  when:
    - instance.type == 'instance'
    - instance.name is defined

# Instance by filter
#
# Returns:
# * aws_vpc_rt_instance_by_filter
- include_tasks: _facts_route_instance_by_filter.yml
  loop_control:
    loop_var: instance
  with_items:
    - "{{ rt.routes }}"
  when:
    - instance.type == 'instance'
    - instance.filter is defined


# Interface by Name tag
#
# Returns:
# * aws_vpc_rt_interface_by_name
- include_tasks: _facts_route_interface_by_name.yml
  loop_control:
    loop_var: interface
  with_items:
    - "{{ rt.routes }}"
  when:
    - interface.type == 'interface'
    - interface.name is defined

# Interface by filter
#
# Returns:
# * aws_vpc_rt_interface_by_filter
- include_tasks: _facts_route_interface_by_filter.yml
  loop_control:
    loop_var: interface
  with_items:
    - "{{ rt.routes }}"
  when:
    - interface.type == 'interface'
    - interface.filter is defined


###
### Merge route array and return: aws_vpc_route_table_routes
###
- name: merge route array
  set_fact:
    aws_vpc_route_table_routes: "{{ aws_vpc_route_table_routes | default([]) + [item] }}"
  with_items:
    - "{{ aws_vpc_rt_igw }}"
    - "{{ aws_vpc_rt_nat_by_name }}"
    - "{{ aws_vpc_rt_nat_by_filter }}"
    - "{{ aws_vpc_rt_peering_by_name }}"
    - "{{ aws_vpc_rt_peering_by_filter }}"
    - "{{ aws_vpc_rt_instance_by_name }}"
    - "{{ aws_vpc_rt_instance_by_filter }}"
    - "{{ aws_vpc_rt_interface_by_name }}"
    - "{{ aws_vpc_rt_interface_by_filter }}"
